### ISSUE TITLE
 Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/android_packages_apps_FairphoneLauncher3#7]
Hello,

2.0 crashes when I launch it on my Android 4.2.1 tablet:
```
E/AndroidRuntime( 2401): FATAL EXCEPTION: main
E/AndroidRuntime( 2401): java.lang.RuntimeException: Unable to start activity ComponentInfo{community.fairphone.fplauncher3/com.fairphone.fplauncher3.Launcher}: java.lang.NullPointerException
E/AndroidRuntime( 2401): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
E/AndroidRuntime( 2401): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 2401): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 2401): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 2401): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2401): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2401): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
E/AndroidRuntime( 2401): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2401): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2401): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 2401): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 2401): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2401): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 2401): 	at com.fairphone.fplauncher3.edgeswipe.a.<init>(Unknown Source)
E/AndroidRuntime( 2401): 	at com.fairphone.fplauncher3.Launcher.onCreate(Unknown Source)
E/AndroidRuntime( 2401): 	at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime( 2401): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime( 2401): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime( 2401): 	... 11 more
W/ActivityManager(  495):   Force finishing activity community.fairphone.fplauncher3/com.fairphone.fplauncher3.Launcher
```

**Comment by Roboe** [comment]
Fairphone Launcher was shipped for Lollipop with the Fairphone 2. It should probably be compatible only from Android 5 onwards.

We could bump its `minSdkVersion` to a Lollipop one or (painfully) debug Android 4 compatiblity.

**Comment by Rudloff** [comment]
I also thought it didn't work because of 4.2 but it works correctly on another one of my devices that runs Android 4.2.4.

**Comment by Roboe** [comment]
Android, :man_shrugging:, hahaha, :joy:

**Comment by ildar** [comment]
@Roboe , may I ask not bumping `minSdkVersion` because:
1. @Rudloff reports that FPL runs good on some JB Androids
2. The choice of launchers running on JB and KK is shrinking while people still using their 5 years old tablets. FPL may be very handy in the situation.
Please?

**Comment by Roboe** [comment]
Hey, @ildar, that was an earlier workaround before I jumped back into maintaining these apps. Thank you for caring and giving real-world context on this issue, :smile:.

@Rudloff, could you test if this issue is still valid on your tablet with the current `master` build? We updated support libraries and build tools. I'll debug the code in the meanwhile.

**Comment by Rudloff** [comment]
Unfortunately, it still crashes.

**Comment by StefanBrand** [comment]
FP2-Launcher 2.1 doesn't crash on my Fairphone 1 running Kitkat 4.4.2.

**Comment by ildar** [comment]
That's good. Yet not good enough to run it on JB :((
