### ISSUE TITLE
Crash when trying to change the wallpaper

### ISSUE THREAD

**Issue by Rudloff** [WeAreFairphone/android_packages_apps_FairphoneLauncher3#9]
If the launcher does not have the storage permission and the user tries to change the wallpaper, the launcher crashes:
```
05-09 17:30:44.333  7983  7994 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=20164, uid=10212 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
05-09 17:30:44.333  7983  7994 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
05-09 17:30:44.333  7983  7994 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
05-09 17:30:44.333  7983  7994 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
05-09 17:30:44.333  7983  7994 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
05-09 17:30:44.333  7983  7994 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
```

It should probably be handled more gracefully.

**Comment by Roboe** [comment]
We should request the user the storage permission to be compatible with Android 6+: https://developer.android.com/training/permissions/requesting
